### ISSUE TITLE
Possible BUG - AmazonConnectS-sfContactTraceRecord

### ISSUE THREAD

**Issue by CristinaCensori** [AmazonConnectSalesforceIntegration/AmazonConnectSalesforceLambda#5]
Hello,

I'm trying to use the new Lambda Function ''/serverlessrepo-AmazonConnectS-sfContactTraceRecord" released in this repository, to import CTR in Salesforce. 
If I place a call and I speak for a few minutes with an agent, the CTR is correctly send to Salesforce, but in case of missed call the CTR is not sent.
In the CloudWath of the Lambda Function ''/serverlessrepo-AmazonConnectS-sfContactTraceRecord" I find this error:

"[ERROR] TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/task/sfContactTraceRecord.py", line 45, in lambda_handler
    raise e
  File "/var/task/sfContactTraceRecord.py", line 40, in lambda_handler
    process_ctr_record(event['record'])
  File "/var/task/sfContactTraceRecord.py", line 56, in process_ctr_record
    create_ctr_record(recordObj)
  File "/var/task/sfContactTraceRecord.py", line 76, in create_ctr_record
    sfRequest[objectnamespace + 'AfterContactWorkEndTimestamp__c'] = ctr['Agent']['AfterContactWorkEndTimestamp']"

Is not possibile to send the CTR for missed call?

**Comment by CristinaCensori** [comment]
Thanks and best regards

**Comment by jeffmodzel** [comment]
Found a similar error but on the Queue field:

[ERROR] TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/task/sfContactTraceRecord.py", line 45, in lambda_handler
    raise e
  File "/var/task/sfContactTraceRecord.py", line 40, in lambda_handler
    process_ctr_record(event['record'])
  File "/var/task/sfContactTraceRecord.py", line 56, in process_ctr_record
    create_ctr_record(recordObj)
  File "/var/task/sfContactTraceRecord.py", line 105, in create_ctr_record
    sfRequest[objectnamespace + 'QueueARN__c'] = ctr['**Queue**']['ARN']
